version: 1.0.0
info:
  site_desc: 一个简约的 Hexo 主题.
  github: https://github.com/LynanBreeze/hexo-theme-linen-doc-zh-CN
  registration: 火星ICP备222222号
navItems:
  - name: 归档
    path: /archives/
topArticles:
  - _posts/quick-start.md
  - _posts/customization.md
  - _posts/write-with-markdown.md
  - _posts/image-grid.md